# Generated by Django 4.2.7 on 2023-11-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='monitores/'),
        ),
    ]
