# Generated by Django 4.2.7 on 2023-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_monitor_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='foto',
        ),
        migrations.AddField(
            model_name='monitor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
