# Generated by Django 4.2.7 on 2023-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_monitor_foto_monitor_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='avatar',
        ),
        migrations.AddField(
            model_name='monitor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
    ]
