# Generated by Django 4.2.7 on 2023-11-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_monitor_avatar_monitor_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
