# Generated by Django 4.2.7 on 2023-11-24 19:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('anio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto')),
            ],
        ),
    ]
