# Generated by Django 4.2.7 on 2023-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='foto',
        ),
        migrations.AddField(
            model_name='monitor',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='productos'),
        ),
    ]
