# Generated by Django 4.2.7 on 2023-12-12 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_alter_monitor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='imagen',
        ),
        migrations.AddField(
            model_name='monitor',
            name='modelo',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placa',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='placa',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
