# Generated by Django 4.2.7 on 2023-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_remove_monitor_imagen_monitor_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='modelo',
        ),
        migrations.AddField(
            model_name='monitor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
        migrations.AlterField(
            model_name='placa',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='placa',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
    ]
