# Generated by Django 4.2.7 on 2023-12-12 20:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
